### ISSUE TITLE
sopport android?

### ISSUE THREAD

**Issue by pankiwi** [zombrodo/plan#3]
i like this lib but has sopport toch android and multi toch?

**Comment by zombrodo** [comment]
Hey!

`plan` doesn't really know where it's being run, and just uses the functions `love.graphics.getWidth` and `love.graphics.getHeight` which as far as I know behaves the same on Android and Desktop, so the rest is really up to you. It doesn't directly use any `love` events, unless you implement hooking into the events (linked below).

Through `Plan.emit` (or `Conainer:emit()`) you can emit events like `touchpressed` or anything you want :) I haven't tested them myself, since I don't develop for Android, but I'm pretty hopeful they'd work 🤞 

Take a look at these:
* `Container:emit`: https://github.com/zombrodo/plan#emitevent-string-
* Hooking into Love : https://github.com/zombrodo/plan#hooking-into-l%C3%B6ve
